debug: false

language: en

# Prevents players from progressing in collections if they are in creative mode
prevent-creative-mode: true

# Prevents players from progressing in collections if they are already at max level
# This is not recommended unless you are not finished with your level (beta testing server etc.)
limit-progress-to-max-requirement: false

# Changing leaderboard options requires a server restart
leaderboard:
  # How many players to display on the leaderboard at all times.
  # Papi placeholders will only be available for the top X.
  cache-size: 10
  # Minimum amount of items that need to be collected to be displayed on the leaderboard for each collection
  min-items-collected: 10

# Always keep at least one alias for each command
command-aliases:
  collections: [ "collections", "collection" ]
  progression: [ "progression" ]

display-components:
  rewards:
    title: "  &7Rewards:&r"
    line: "    {reward}"

level-up-message:
  enabled: true
  open-menu-when-clicked: true
  message:
    - "&3&m----------------------------------------&r"
    - ' '
    - "  &f&l{collection_name} collection level up &6&l{level}&r"
    - ' '
    - "component:rewards"
    - ' '
    - "&3&m----------------------------------------"

discover-message:
  enabled: false
  open-menu-when-clicked: true
  message:
    - "&3&m----------------------------------------&r"
    - ' '
    - "  &f&lCollection discovered&r"
    - "    &e&l{collection_name}&r"
    - ' '
    - "&3&m----------------------------------------"

discover-sound:
  enabled: false
  sound: "entity.player.levelup"
  volume: 1
  pitch: 1

category-level-up-message:
  enabled: true
  open-menu-when-clicked: true
  message:
    - "&3&m----------------------------------------&r"
    - ' '
    - "  &f&l{category_name} milestone reached &6&l{percent}%&r"
    - ' '
    - "component:rewards"
    - ' '
    - "&3&m----------------------------------------"

level-up-sound:
  enabled: true
  sound: "entity.player.levelup"
  volume: 1
  pitch: 1

# These will be default values for all collections
# You can override these values in the collection config
global-level-matchers:
  default:
    interval: 1
    priority: 0
    rewards:
      my-money-reward:
        type: money
        formula: "1000 * {level_raw} * 2.5"
        display: "&8+&a{value_formatted}$"
      my-xp-reward:
        type: levels_xp
        formula: "{level_raw} * 2"
        display: "&8+&b{value_formatted} Global XP"

# Don't touch this unless you know what you're doing
config-version: 5