triggers: [ entity_loot ]
types:
  - "minecraft:rotten_flesh"

name: "Rotten flesh"

menu-item:
  material: ROTTEN_FLESH

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 50
  - 100
  - 250
  - 1000
  - 2500
  - 5000
  - 10000

use-global-level-matchers: true